/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/Dashboard/home': RouteRecordInfo<'/Dashboard/home', '/Dashboard/home', Record<never, never>, Record<never, never>>,
    '/Users/AcessLevel': RouteRecordInfo<'/Users/AcessLevel', '/Users/AcessLevel', Record<never, never>, Record<never, never>>,
    '/Users/List': RouteRecordInfo<'/Users/List', '/Users/List', Record<never, never>, Record<never, never>>,
  }
}
